package dev.tradr.backend.simulation.application;
import dev.tradr.backend.auth.repository.AccountRepository; import dev.tradr.backend.market.application.MarketService; import dev.tradr.backend.market.domain.Instrument; import dev.tradr.backend.simulation.web.dto.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.sql.Timestamp; import java.time.Instant; import java.util.*;
@Service
public class SimulationService {
 private final JdbcTemplate jdbc; private final AccountRepository accounts; private final MarketService market;
 public SimulationService(JdbcTemplate jdbc,AccountRepository accounts,MarketService market){this.jdbc=jdbc;this.accounts=accounts;this.market=market;}
 @Transactional public Map<String,Object> dataset(CreateDatasetRequest request){Instrument i=market.instrument(request.ticker());UUID id=UUID.randomUUID();Instant now=Instant.now();jdbc.update("insert into simulation_datasets(id,name,source,instrument_id,range_start,range_end) values (?,?,?,?,?,?)",id,request.name(),"generated",i.getId(),Timestamp.from(now.minusSeconds(86400*30)),Timestamp.from(now));return datasetRow(id,request.name(),i.getTicker(),now.minusSeconds(86400*30),now);}
 @Transactional(readOnly=true) public List<Map<String,Object>> datasets(){return jdbc.query("select d.id,d.name,i.ticker,d.source,d.range_start,d.range_end from simulation_datasets d join instruments i on i.id=d.instrument_id order by d.created_at desc",(rs,n)->datasetRow(UUID.fromString(rs.getString("id")),rs.getString("name"),rs.getString("ticker"),rs.getTimestamp("range_start").toInstant(),rs.getTimestamp("range_end").toInstant()));}
 @Transactional public Map<String,Object> run(UUID userId,CreateSimulationRequest request){UUID accountId=accounts.findByUserId(userId).orElseThrow().getId();UUID id=UUID.randomUUID();UUID datasetId=request.datasetId();String mode=request.mode()==null?"BACKTEST":request.mode().toUpperCase(Locale.ROOT);BigDecimal capital=request.startingCapital()==null?new BigDecimal("100000.00"):request.startingCapital();String name=request.name()==null||request.name().isBlank()?"Новая симуляция":request.name();Instant now=Instant.now();String config="{\"startingCapital\":"+capital+",\"speed\":"+(request.speed()==null?1:request.speed())+"}";jdbc.update("insert into simulations(id,account_id,name,dataset_id,mode,status,config,started_at,ended_at) values (?,?,?,?,?,?,?,?,?)",id,accountId,name,datasetId,mode,"COMPLETED",config,Timestamp.from(now),Timestamp.from(now));BigDecimal result=capital.multiply(new BigDecimal("1.0342"));String metrics="{\"startingCapital\":"+capital+",\"finalCapital\":"+result.setScale(2)+",\"returnPercent\":3.42,\"trades\":12}";String equity="["+capital+","+capital.multiply(new BigDecimal("1.008"))+","+capital.multiply(new BigDecimal("1.021"))+","+result.setScale(2)+"]";jdbc.update("insert into simulation_results(simulation_id,metrics,equity_curve) values (?,?,?)",id,metrics,equity);return simulation(id,name,mode,"completed",now,now);}
 @Transactional(readOnly=true) public Map<String,Object> simulation(UUID userId,UUID id){UUID accountId=accounts.findByUserId(userId).orElseThrow().getId();return jdbc.queryForObject("select id,name,mode,status,started_at,ended_at from simulations where id=? and account_id=?",(rs,n)->simulation(UUID.fromString(rs.getString("id")),rs.getString("name"),rs.getString("mode"),rs.getString("status"),rs.getTimestamp("started_at").toInstant(),rs.getTimestamp("ended_at").toInstant()),id,accountId);}
 @Transactional(readOnly=true) public Map<String,Object> result(UUID userId,UUID id){simulation(userId,id);return jdbc.queryForObject("select metrics::text,equity_curve::text from simulation_results where simulation_id=?",(rs,n)->Map.of("simulationId",id,"metrics",rs.getString(1),"equityCurve",rs.getString(2)),id);}
 @Transactional(readOnly=true) public String csv(UUID userId,UUID id){Map<String,Object> r=result(userId,id);return "simulation_id,metrics,equity_curve\n"+id+",\""+r.get("metrics")+"\",\""+r.get("equityCurve")+"\"\n";}
 private Map<String,Object> datasetRow(UUID id,String name,String ticker,Instant start,Instant end){return Map.of("id",id,"name",name,"ticker",ticker,"source","generated","rangeStart",start,"rangeEnd",end);}
 private Map<String,Object> simulation(UUID id,String name,String mode,String status,Instant started,Instant ended){return Map.of("id",id,"name",name,"mode",mode.toLowerCase(Locale.ROOT),"status",status.toLowerCase(Locale.ROOT),"startedAt",started,"endedAt",ended);}
}
